# Generated by Django 4.0 on 2024-04-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIapp', '0004_imageelement_textelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiTextElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
