# Generated by Django 5.0.3 on 2024-03-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIapp', '0002_imageai_image_ai'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageai',
            options={'verbose_name': 'Imageai', 'verbose_name_plural': 'Obrazy AI'},
        ),
    ]
